# Generated by Django 4.2.29 on 2026-04-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0002_locker_updated_at_alter_locker_locker_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='locker',
            name='locker_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='locker',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('inactive', 'Inactive')], default='available', max_length=20),
        ),
    ]
